name: SimplePlugins
description: Plugin management functions for enabling/disabling.
version: %VERSION%
depend: [MessageManager]
main: edgruberman.bukkit.simpleplugins.Main
author: EdGruberman (ed@rjump.com)
commands:
    plugin:
        description: Manage Bukkit plugins.
        usage: |
            /<command> - Show current plugins.
            /<command> enable|disable <Plugin>
            /<command> restart <Plugin>